### ISSUE TITLE
[ISSUE] 어떤 것이든 설정으로 다뤄보자

### ISSUE THREAD

**Issue by lette1394** [auctionari/api-server#2]
### 목표

아래 세 가지 모두 지원 

- `jar` 실행 파일 argument로 넘겨주기
- 특정 `.yml` 지정해주기 
  - 테스트에 유용할 것으로 예상
  - `java -jar app.jar --config-file ./config.yml`
- configuration server url 명시
  - 미리 정의된 endpoint에 `GET` 요청을 하면 yaml 파일이 나오는 식
  - `java -jar app.jar --config-server http://{{some-ec2-host}}/config`

### 구현
- hot-reloading 지원
- 구현체는 손수 만들어 보자
	- 많고 많은 `yaml` parser들을 이용
 		- `json`, `xml`, 무엇이든 괜찮다
    - 1> validation: `yaml` 형식이 맞는지 검사
    - 2> load: `yaml` 메모리에 올림
    - 3> swap: 기존에 serving 되고 있던 설정 파일을 atomic 하게 swap
- `yaml` 파일은 설정 파일인 만큼, 한 번 결정하면 구조를 변경하기 힘들다. 따라서
  - version 명시
  - 선언적으로 
    - 어떻게 해라가 아닌, 무엇을 해라
  - 확장성 있게 -> 특정 logic 의존적이게 생성 X 
    - `option`, `host-v1` 같은 필드는 지양

  
yaml example

```yaml
---
version: # version is never changed
  number: 1.0
  scheme: 
    url: http://sample.com/scheme/1.0

children:
  - hosts:
    - http://192.168.0.12
    - http://192.168.0.13
    - http://192.168.0.14
    - http://192.168.0.15
  
proxy:
  mode: concurrency
  at-once: 4
reload:
  enable: true
  mode: fail-recovery #(fail-recovery | rollback | shutdown-if-fail)
config:
  server:
    url: http://sample.com
    endpoint: /config
    method: GET
    port: 9000

```
